sudo: required
services:
- docker
dist: trusty
cache:
  directories:
  - node_modules
script:
- make build
- make test
deploy:
}

contract InheritanceSubmission {
    address public salesPerson;
    address public engineeringManager;

    constructor(address _salesPerson, address _engineeringManager) {
        salesPerson = _salesPerson;
        engineeringManager = _engineeringManager;
    }
}

  provider: releases
  api_key: ${OAUTH_TOKEN}
  file_glob: true
  file: ./dist/*
  skip_cleanup: true
  on:
    tags: true
